name: Deploy to VPS

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '22'
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Build application
      run: npm run build
      env:
        NEXT_PUBLIC_EMAILJS_SERVICE_ID: ${{ secrets.EMAILJS_SERVICE_ID }}
        NEXT_PUBLIC_EMAILJS_TEMPLATE_ID: ${{ secrets.EMAILJS_TEMPLATE_ID }}
        NEXT_PUBLIC_EMAILJS_PUBLIC_KEY: ${{ secrets.EMAILJS_PUBLIC_KEY }}
        
    - name: Prepare VPS directory
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.VPS_HOST }}
        username: ${{ secrets.VPS_USERNAME }}
        password: ${{ secrets.VPS_PASSWORD }}
        port: ${{ secrets.VPS_PORT }}
        script: |
          # Créer le dossier de déploiement avec les bonnes permissions
          sudo mkdir -p /opt/portfolio-app
          sudo chown deploy:deploy /opt/portfolio-app
          sudo chmod 755 /opt/portfolio-app
          
          # Arrêter le conteneur existant s'il existe
          cd /opt/portfolio-app
          if [ -f "docker-compose.yml" ]; then
            docker-compose down || true
          fi
          
          # Sauvegarder l'ancienne version
          if [ -d "backup" ]; then
            rm -rf backup
          fi
          mkdir -p backup
          if [ -f "package.json" ]; then
            cp -r . backup/$(date +%Y%m%d_%H%M%S) || true
          fi
          
          # Nettoyer les anciens builds
          docker system prune -f
          
    - name: Copy files to VPS
      uses: appleboy/scp-action@v0.1.7
      with:
        host: ${{ secrets.VPS_HOST }}
        username: ${{ secrets.VPS_USERNAME }}
        password: ${{ secrets.VPS_PASSWORD }}
        port: ${{ secrets.VPS_PORT }}
        source: "."
        target: "/opt/portfolio-app"
        strip_components: 0
        overwrite: true
        rm: true
        
    - name: Verify files copied
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.VPS_HOST }}
        username: ${{ secrets.VPS_USERNAME }}
        password: ${{ secrets.VPS_PASSWORD }}
        port: ${{ secrets.VPS_PORT }}
        script: |
          cd /opt/portfolio-app
          echo "📁 Contenu du dossier :"
          ls -la
          echo "📄 Vérification des fichiers essentiels :"
          [ -f "package.json" ] && echo "✅ package.json trouvé" || echo "❌ package.json manquant"
          [ -f "docker-compose.yml" ] && echo "✅ docker-compose.yml trouvé" || echo "❌ docker-compose.yml manquant"
          [ -f "Dockerfile" ] && echo "✅ Dockerfile trouvé" || echo "❌ Dockerfile manquant"
        
    - name: Start application
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.VPS_HOST }}
        username: ${{ secrets.VPS_USERNAME }}
        password: ${{ secrets.VPS_PASSWORD }}
        port: ${{ secrets.VPS_PORT }}
        script: |
          cd /opt/portfolio-app
          
          # Donner les permissions au user deploy
          sudo chown -R deploy:deploy /opt/portfolio-app
          sudo chmod -R 755 /opt/portfolio-app
          
          # Vérifier que Docker est disponible
          docker --version || exit 1
          docker-compose --version || exit 1
          
          # Build et démarrer les conteneurs
          echo "🐳 Démarrage des conteneurs..."
          docker-compose up -d --build
          
          # Attendre que l'application démarre
          echo "⏳ Attente du démarrage de l'application..."
          sleep 15
          
          # Vérifier que l'application démarre
          echo "🔍 Vérification de la santé de l'application..."
          for i in {1..5}; do
            if curl -f http://localhost:3002/api/health; then
              echo "✅ Application démarrée avec succès"
              break
            else
              echo "⏳ Tentative $i/5 - Application pas encore prête..."
              sleep 5
            fi
          done
          
          # Vérification finale
          curl -f http://localhost:3002/api/health || exit 1
          
          # Nettoyer les anciens builds
          docker system prune -f
          
    - name: Notify deployment success
      if: success()
      run: |
        echo "✅ Déploiement réussi sur ${{ secrets.VPS_HOST }}"
        echo "🌐 Application accessible sur le port 3002"
        
    - name: Notify deployment failure
      if: failure()
      run: |
        echo "❌ Échec du déploiement sur ${{ secrets.VPS_HOST }}"
        echo "🔍 Vérifiez les logs sur le serveur" 