name: Deploy to VPS

on:
  push:
    branches:
      - main
    tags:
      - '*'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to prod server
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.DEPLOY_HOST }}
          username: ${{ secrets.DEPLOY_USER }}
          port: ${{ secrets.DEPLOY_PORT }}
          key: ${{ secrets.DEPLOY_SSH_KEY }}
          script: |
            docker pull ${{ secrets.DOCKERHUB_USERNAME }}/portfolio-app:${GITHUB_REF##*/}
            docker stop portfolio || true
            docker rm portfolio || true
            docker run -d \
              --name portfolio \
              -p ${{ secrets.APP_PORT }}:3000 \
              --restart unless-stopped \
              ${{ secrets.DOCKERHUB_USERNAME }}/portfolio-app:${GITHUB_REF##*/}
