name: Rollback VPS

on:
  workflow_dispatch:
    inputs:
      backup_date:
        description: 'Date de sauvegarde (YYYYMMDD_HHMMSS)'
        required: true
        default: 'latest'

jobs:
  rollback:
    runs-on: ubuntu-latest
    
    steps:
    - name: Rollback to backup
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.VPS_HOST }}
        username: ${{ secrets.VPS_USERNAME }}
        password: ${{ secrets.VPS_PASSWORD }}
        port: ${{ secrets.VPS_PORT }}
        script: |
          cd /opt/portfolio-app
          
          # Arrêter l'application actuelle
          docker-compose down
          
          # Trouver la sauvegarde la plus récente si 'latest'
          if [ "${{ github.event.inputs.backup_date }}" = "latest" ]; then
            BACKUP_DIR=$(ls -t backup/ | head -1)
          else
            BACKUP_DIR="${{ github.event.inputs.backup_date }}"
          fi
          
          if [ ! -d "backup/$BACKUP_DIR" ]; then
            echo "❌ Sauvegarde backup/$BACKUP_DIR non trouvée"
            exit 1
          fi
          
          echo "🔄 Rollback vers backup/$BACKUP_DIR"
          
          # Sauvegarder l'état actuel
          cp -r . backup/failed_$(date +%Y%m%d_%H%M%S)
          
          # Restaurer la sauvegarde
          rm -rf .next node_modules package-lock.json
          cp -r backup/$BACKUP_DIR/* .
          
          # Redémarrer l'application
          docker-compose up -d --build
          
          # Vérifier que l'application démarre
          sleep 10
          curl -f http://localhost:3002/api/health || exit 1
          
          echo "✅ Rollback réussi vers backup/$BACKUP_DIR"
          
    - name: List available backups
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.VPS_HOST }}
        username: ${{ secrets.VPS_USERNAME }}
        password: ${{ secrets.VPS_PASSWORD }}
        port: ${{ secrets.VPS_PORT }}
        script: |
          cd /opt/portfolio-app
          echo "📋 Sauvegardes disponibles :"
          ls -la backup/ || echo "Aucune sauvegarde trouvée" 